### ISSUE TITLE
No link to javaparser/javaparser

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser-website#4]

**Comment by ftomassetti** [comment]
I think that most people are just interested in using JavaParser, so they should not go to GitHub.
For the people who knows GitHub we have the buttons, which looks very familiar and bring to the GitHub projects.

I could add an explicit section on contributing (with prominent links to GitHub) under about or create a new page named "Contributing". What do you think?

**Comment by matozoid** [comment]
Hmmm, I think I'd rather keep contribution info where it is, since github points people to it when you create a new issue. Or you must like keeping information in sync :)

**Comment by DeepSnowNeeL** [comment]
do keep the actual Dependency Management block though

**Comment by matozoid** [comment]
I hope @ftomassetti is making something that is maintainable. No copy/paste please!

**Comment by ftomassetti** [comment]
From my perspective the website should be intended for people mostly interested in just using JavaParser. Some of them could be interested in contributing also so that contributing page would basically say "if you want to contribute you need to go on GitHub and read our contributing guide. GitHub works like this..." follows a 3-5 lines explanation of GitHub.

People looking on GitHub should be instead more experienced developers or more familiar with open-source and GitHub so the contributing guide there is and would remain more detailed and specific.

About maintenance: currently we have 3 html files. You change them, push and the changes go live. From that point of view maintenance is easy because deploying is easy. I imagine these pages will not change much over time. From time to time we may want to change the versions of references but basically this is it. I would first plan on getting the content right then if we can make some changes to make more mantainable (like using templates, so changes to the header have not to be duplicated) I would do them later, once we agreed on the structure of the website and see what is going to change in the future

**Comment by matozoid** [comment]
Alright :)

**Comment by ftomassetti** [comment]
I have added a link in the navigation bar
